meta_product_name: "Vocation"
meta_title: "Vocation - Improve your english!"
meta_description: "Improve your English. Vocation brings you an efficient method to learn vocabulary"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards


